// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hosted project defaults (fallback when no local override is set)
const HOSTED_SUPABASE_URL = "https://zjymowjrqidmgslauauv.supabase.co";
const HOSTED_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqeW1vd2pycWlkbWdzbGF1YXV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTg5NDksImV4cCI6MjA2NTUzNDk0OX0.Vgr0rW3Xi6eoD-hKX5R_4IeL5ABNPP0w80EUVzUAG8k";

function resolveSupabaseConfig() {
  const hasWindow = typeof window !== 'undefined';
  const isLocalhost = hasWindow && /^(localhost|127\.0\.0\.1)$/i.test(window.location.hostname);
  const localUrl = hasWindow ? localStorage.getItem('LOCAL_SUPABASE_URL') : null;
  const localAnon = hasWindow ? localStorage.getItem('LOCAL_SUPABASE_ANON_KEY') : null;

  if (isLocalhost && localUrl && localAnon) {
    console.info('[Supabase] Using LOCAL Supabase from localStorage override:', localUrl);
    return { url: localUrl, anonKey: localAnon };
  }

  console.info('[Supabase] Using HOSTED Supabase project');
  return { url: HOSTED_SUPABASE_URL, anonKey: HOSTED_SUPABASE_ANON_KEY };
}

const { url, anonKey } = resolveSupabaseConfig();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(url, anonKey);
